## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

branches:
  only:
  - master
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - i686

julia:
  - "1.0"
  - "1" # currently 1.5
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly

  # Test 32-bit only on Linux
  exclude:
    - arch: i686
      os: osx
    - arch: i686
      os: windows

codecov: true
coveralls: true

notifications:
  email: false
