language: julia
julia:
  - 0.6
  - nightly
notifications:
    email: false
sudo: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.test("Coverage"; coverage=true)'
  - julia -e 'using Coverage; Coveralls.submit(process_folder())'
  - julia -e 'using Coverage; Codecov.submit(process_folder())'
